### ISSUE TITLE
How to bind an interface to a concrete class dynamically.

### ISSUE THREAD

**Issue by mtvbrianking** [maxalmonte14/weather-cli#1]
Hello Max,

Was wondering how do I bind an interface to the class dynamically!

In the example [FakeServiceProvider](https://github.com/maxalmonte14/weather-cli/blob/master/tests/Fakes/FakeServiceProvider.php) only providers a **success test response**, what if I wanted to test a **unsuccessful response** as well.
Like when the external API is _unreachable_, or explicitly returns _error response_.

**Comment by maxalmonte14** [comment]
You can always mock `App\Http\HttpClientInterface` and replace the previous bind class.

```php
/** @test */
public function foo()
{
    $mock = \Mockery::mock('App\Http\HttpClientInterface');

    // Here you override the methods you want.
    // ...

    // Now you bind the mock to the interface
    $this->app->bind('App\Http\HttpClientInterface', $mock);

    // That should do
}
```

**Comment by mtvbrianking** [comment]
Thanks. 

Also wanted to say the [article](https://devalmonte.com/blog/2018-11-14/testing-laravel-zero-dynamic-commands) is great.

**Comment by maxalmonte14** [comment]
Thank you Brian, I'm glad you liked the article 😄
